#ifndef _FERRIT_PIO_SPI_H_
#define _FERRIT_PIO_SPI_H_

#include <stdint.h>
#include <stddef.h>
#include "hardware/pio.h"
#include "ferrit_spi.pio.h"   // generated by pioasm from ferrit_spi.pio

typedef struct {
    PIO  pio;
    uint sm;
} pio_spi_t;

void pio_spi_init(pio_spi_t *inst, PIO pio, uint sm,
                  uint pin_sck, uint pin_mosi, uint pin_miso,
                  float clk_div);

void pio_spi_write_read_blocking(const pio_spi_t *inst,
                                 const uint8_t *src, uint8_t *dst,
                                 size_t len);

void pio_spi_write_blocking(const pio_spi_t *inst,
                            const uint8_t *src, size_t len);

void pio_spi_read_blocking(const pio_spi_t *inst,
                           uint8_t tx_byte, uint8_t *dst, size_t len);

#endif // _FERRIT_PIO_SPI_H_
